sample_job:
  runs-on: ubuntu-latest
  name: Pytest passing tests
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: "3.11.8"
    - name: Checkout
      uses: actions/checkout@v2
    - name: Pytest Action Step
      id: pytest
      uses: paolorechia/fast-pytest-github-action@develop
      with:
        requirements_file: "requirements.txt"
