name: Visual Testing

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  visual-testing:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '>=22'

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Start local server
        run: |
          npx quartz build --serve &
          SERVER_PID=$!
          echo "SERVER_PID=$SERVER_PID" >> $GITHUB_ENV
          
      - name: Wait for server
        run: |
          # Wait for the server to be ready
          while ! nc -z localhost 8080; do
            sleep 0.1 # Check every 100ms
            # Check if server is still running
            if ! ps -p ${{ env.SERVER_PID }} > /dev/null; then
              echo "Server failed to start"
              exit 1
            fi
          done
          echo "Server is ready"

      # - name: Run visual tests
      #   run: npx playwright test 
      #   env:
      #     ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
      #     CI: true